'use client';

import React, { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Suspense } from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Sparkles, Loader2, ShieldAlert, KeyRound } from 'lucide-react';
import { safeNextPath } from '@/lib/auth/safe-redirect';

/**
 * Published credentials for the judged demo. They must match DASHBOARD_USERNAME and
 * DASHBOARD_PASSWORD on the deployment, or the button will answer 401 in front of the person it
 * exists to help.
 */
const DEMO_USERNAME = 'admin';
const DEMO_PASSWORD = 'razorpay@123';

function LoginForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  // Never redirect anywhere the proxy did not send us. See safeNextPath: an unchecked `next`
  // is an open redirect, and a login page is the worst place to have one.
  const nextPath = safeNextPath(searchParams.get('next'));

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const signIn = async (asUsername: string, asPassword: string) => {
    setIsSubmitting(true);
    setError(null);

    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username: asUsername, password: asPassword }),
      });
      const json = await res.json();

      if (json.success) {
        router.push(nextPath);
        router.refresh();
      } else {
        setError(json.error?.message || 'Login failed');
      }
    } catch {
      setError('Could not reach the server. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await signIn(username, password);
  };

  /**
   * One-click access for an evaluator (RA-27).
   *
   * The credentials are in the page source, which is the point: a judge with the URL should not
   * have to ask anyone for a password. That only makes sense because this deployment holds
   * synthetic data — the whole batch is generated by `db/seed.ts` — and it is why the button is
   * rendered only when NEXT_PUBLIC_DEMO_LOGIN is set. A deployment with real customer records
   * leaves it unset and the button does not exist.
   */
  const demoLoginEnabled = process.env.NEXT_PUBLIC_DEMO_LOGIN === 'true';
  const handleDemoLogin = () => signIn(DEMO_USERNAME, DEMO_PASSWORD);

  return (
    <div className="min-h-screen flex items-center justify-center bg-zinc-50/60 dark:bg-zinc-950 px-4">
      <Card className="w-full max-w-sm border-zinc-200 dark:border-zinc-800 shadow-xs">
        <CardHeader className="text-center space-y-2">
          <div className="w-10 h-10 mx-auto rounded-xl bg-gradient-to-tr from-blue-600 via-indigo-600 to-violet-600 flex items-center justify-center text-white shadow-md shadow-indigo-500/20">
            <Sparkles className="w-5 h-5" />
          </div>
          <CardTitle className="text-lg font-bold text-zinc-900 dark:text-zinc-50">
            Recover<span className="text-indigo-600 dark:text-indigo-400">AI</span> Dashboard
          </CardTitle>
          <CardDescription className="text-xs text-zinc-500">
            Sign in to view customer records, metrics, and run recovery.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-3">
            <Input
              type="text"
              placeholder="Username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              autoComplete="username"
              required
            />
            <Input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              autoComplete="current-password"
              required
            />

            {error && (
              <div className="flex items-start gap-2 text-xs text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-950/30 rounded-lg p-2.5">
                <ShieldAlert className="w-3.5 h-3.5 mt-0.5 shrink-0" />
                <span>{error}</span>
              </div>
            )}

            <Button type="submit" disabled={isSubmitting} className="w-full bg-indigo-600 hover:bg-indigo-700 text-white">
              {isSubmitting ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Signing in...
                </>
              ) : (
                'Sign in'
              )}
            </Button>
          </form>

          {demoLoginEnabled && (
            <>
              <div className="flex items-center gap-3 my-4">
                <span className="h-px flex-1 bg-zinc-200 dark:bg-zinc-800" />
                <span className="text-[10px] uppercase tracking-wide text-zinc-400">
                  Evaluating this project?
                </span>
                <span className="h-px flex-1 bg-zinc-200 dark:bg-zinc-800" />
              </div>

              <Button
                type="button"
                variant="outline"
                onClick={handleDemoLogin}
                disabled={isSubmitting}
                className="w-full border-indigo-200 dark:border-indigo-900/50 text-indigo-700 dark:text-indigo-300 hover:bg-indigo-50 dark:hover:bg-indigo-950/30"
              >
                <KeyRound className="w-4 h-4 mr-2" />
                Sign in as evaluator
              </Button>

              <p className="mt-2 text-[11px] leading-relaxed text-zinc-500 text-center">
                Signs in as <code className="font-mono">{DEMO_USERNAME}</code> /{' '}
                <code className="font-mono">{DEMO_PASSWORD}</code>. Every record behind this login
                is synthetic — the batch is generated by the seed script, not real customers.
              </p>
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

export default function LoginPage() {
  return (
    <Suspense fallback={null}>
      <LoginForm />
    </Suspense>
  );
}
